name: sakura

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repository
       uses: actions/checkout@v3
     - name: Deploy
       uses: sgmtg/board_manga_pair@develop
       with:
         host: ${{ secrets.SERVER_HOST }}
         username: ${{ secrets.SERVER_USERNAME }}
         password: ${{ secrets.SERVER_PASS }}
         script: |
           cd ${{ secrets.SERVER_DEPLOY_DIR }}
           git pull origin develop         
